//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Span_Aid
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealingRadius_Ticket
    {
        public long HR_Ticket_Id { get; set; }
        public string HR_Ticket_Number { get; set; }
        public string HR_User_Name { get; set; }
        public string HR_Email_Address { get; set; }
        public string HR_Appoinment_Number { get; set; }
        public string HR_Ticket_Description { get; set; }
        public string HR_Ticket_Status { get; set; }
        public bool HR_Is_Deleted { get; set; }
        public System.DateTime HR_Ticket_Create_Date { get; set; }
        public System.DateTime HR_Ticket_Update_Date { get; set; }
    }
}
